version: '3.7'

volumes:
  peer0.berlin.universidades.com:

networks:
  test:
    name: universidades_network

services:

  couchdb2:
    container_name: couchdb2
    image: couchdb:3.1.1
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "9984:5984"
    networks:
      - test

  peer0.berlin.universidades.com:
    container_name: peer0.berlin.universidades.com
    image: hyperledger/fabric-peer:2.3.3
    labels:
      service: hyperledger-fabric
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=universidades_network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.berlin.universidades.com
      - CORE_PEER_ADDRESS=peer0.berlin.universidades.com:2051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:2051
      - CORE_PEER_CHAINCODEADDRESS=peer0.berlin.universidades.com:2052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:2052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.berlin.universidades.com:2051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.berlin.universidades.com:2051
      - CORE_PEER_LOCALMSPID=BerlinMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:12051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/berlin.universidades.com/peers/peer0.berlin.universidades.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/berlin.universidades.com/peers/peer0.berlin.universidades.com/tls:/etc/hyperledger/fabric/tls
        - peer0.berlin.universidades.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 2051:2051
      - 12051:12051
    networks:
      - test
    depends_on:
      - couchdb2
