---
################################################################################
#   Section: Organizations
################################################################################
Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ../organizations/ordererOrganizations/universidades.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

        OrdererEndpoints:
            - orderer.universidades.com:7050

    - &Madrid
        Name: MadridMSP
        ID: MadridMSP

        MSPDir: ../organizations/peerOrganizations/madrid.universidades.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('MadridMSP.admin', 'MadridMSP.peer', 'MadridMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('MadridMSP.admin', 'MadridMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('MadridMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('MadridMSP.peer')"

    - &Bogota
        Name: BogotaMSP
        ID: BogotaMSP

        MSPDir: ../organizations/peerOrganizations/bogota.universidades.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('BogotaMSP.admin', 'BogotaMSP.peer', 'BogotaMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('BogotaMSP.admin', 'BogotaMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('BogotaMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('BogotaMSP.peer')"

################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities
################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer.universidades.com:7050
    EtcdRaft:
        Consenters:
        - Host: orderer.universidades.com
          Port: 7050
          ClientTLSCert: ../organizations/ordererOrganizations/universidades.com/orderers/orderer.universidades.com/tls/server.crt
          ServerTLSCert: ../organizations/ordererOrganizations/universidades.com/orderers/orderer.universidades.com/tls/server.crt

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

################################################################################
#   CHANNEL
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Profile
################################################################################
Profiles:

    UniversidadesGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Madrid
                - *Bogota
            Capabilities: *ApplicationCapabilities
